import { notFound } from "next/navigation";
import { requireUserContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { formatDate, formatMoney } from "@/lib/formatting";
import { isUuid } from "@/lib/auth/access-errors";
export default async function InvoicePrint({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!isUuid(id)) notFound();
  const c = await requireUserContext("finance.read");
  if (!c.active_school_id) notFound();
  const s = await createClient();
  const { data: i } = await (s.from("invoices") as any)
    .select(
      "id,invoice_number,invoice_date,due_date,subtotal,discount_amount,tax_amount,total_amount,paid_amount,balance_due,status,schools(name,email,phone),students(admission_number,people(first_name,last_name)),academic_years(name),terms(name)"
    )
    .eq("id", id)
    .eq("school_id", c.active_school_id)
    .maybeSingle();
  if (!i) notFound();
  const { data: lines } = await (s.from("invoice_lines") as any)
    .select("id,description,quantity,unit_amount,discount_amount,tax_amount,line_total")
    .eq("invoice_id", id)
    .eq("school_id", c.active_school_id);
  return (
    <article>
      <header className="flex justify-between border-b-2 pb-5">
        <div>
          <h1 className="text-3xl font-black">{i.schools?.name}</h1>
          <p>
            {i.schools?.email} · {i.schools?.phone}
          </p>
        </div>
        <div className="text-right">
          <p className="text-2xl font-bold">INVOICE</p>
          <p>{i.invoice_number}</p>
        </div>
      </header>
      <section className="grid grid-cols-2 gap-6 py-6">
        <div>
          <p className="text-xs uppercase text-slate-500">Bill to</p>
          <p className="mt-1 font-bold">
            {i.students?.people?.first_name} {i.students?.people?.last_name}
          </p>
          <p>{i.students?.admission_number}</p>
        </div>
        <div className="text-right">
          <p>Invoice date: {formatDate(i.invoice_date)}</p>
          <p>Due date: {formatDate(i.due_date)}</p>
          <p>
            Academic period: {i.academic_years?.name} · {i.terms?.name ?? ""}
          </p>
        </div>
      </section>
      <table className="w-full border-collapse">
        <thead>
          <tr className="bg-slate-100">
            {["Description", "Qty", "Unit price", "Discount", "Tax", "Total"].map((x) => (
              <th className="border p-3 text-left" key={x}>
                {x}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {(lines ?? []).map((l: any) => (
            <tr key={l.id}>
              <td className="border p-3">{l.description}</td>
              <td className="border p-3">{l.quantity}</td>
              <td className="border p-3">{formatMoney(l.unit_amount)}</td>
              <td className="border p-3">{formatMoney(l.discount_amount)}</td>
              <td className="border p-3">{formatMoney(l.tax_amount)}</td>
              <td className="border p-3 font-bold">{formatMoney(l.line_total)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="ml-auto mt-6 w-full max-w-sm space-y-2">
        <R l="Subtotal" v={formatMoney(i.subtotal)} />
        <R l="Discount" v={formatMoney(i.discount_amount)} />
        <R l="Tax" v={formatMoney(i.tax_amount)} />
        <R l="Total" v={formatMoney(i.total_amount)} bold />
        <R l="Paid" v={formatMoney(i.paid_amount)} />
        <R l="Balance due" v={formatMoney(i.balance_due)} bold />
      </div>
      <footer className="mt-12 border-t pt-4 text-sm text-slate-500">
        This invoice was generated by SchoolDB and reflects the current posted ledger state.
      </footer>
    </article>
  );
}
function R({ l, v, bold = false }: { l: string; v: string; bold?: boolean }) {
  return (
    <div className="flex justify-between border-b py-2">
      <span>{l}</span>
      <span className={bold ? "font-black" : "font-semibold"}>{v}</span>
    </div>
  );
}
