// Auto-generated by Supabase. This is a stub for development.
// Run: npm run db:types to regenerate with actual schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, any>
        Insert: Record<string, any>
        Update: Record<string, any>
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, any>
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, any>
        Returns: any
      }
    }
    Enums: {
      [key: string]: string
    }
  }
}

export type PublicTableName = string

export interface Profile {
  id: string
  email: string
  first_name: string | null
  last_name: string | null
  is_active: boolean
  must_change_password: boolean
  created_at: string
  updated_at: string
}
