"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { createEmployee, linkExistingTeacherPortalAccess, retryTeacherPortalAccess, type TeacherCreateState } from "@/app/app/staff/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input, Label, Select } from "@/components/ui/input";

export function TeacherCreateForm({ campuses, departments }: { campuses: any[]; departments: any[] }) {
  const initialState: TeacherCreateState = { status: "idle" };
  const [state, action, pending] = useActionState(createEmployee, initialState);
  const [retry, retryAction, retryPending] = useActionState(retryTeacherPortalAccess, initialState);
  const [link, linkAction, linkPending] = useActionState(linkExistingTeacherPortalAccess, initialState);
  const [teacher, setTeacher] = useState(false); const [portal, setPortal] = useState(false); const [shown, setShown] = useState(true);
  const result = link.status !== "idle" ? link : retry.status !== "idle" ? retry : state;
  return <form action={action} className="space-y-6">
    {result.message ? <p className={`rounded-xl p-3 text-sm ${result.status === "error" || result.status === "portal-failure" ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{result.message}</p> : null}
    <Card><CardHeader><h2 className="font-semibold">Personal information</h2></CardHeader><CardContent className="grid gap-5 md:grid-cols-3"><F n="first_name" l="First name"/><F n="middle_name" l="Middle name" o/><F n="last_name" l="Last name"/><F n="preferred_name" l="Preferred name" o/><Sel n="gender" l="Gender" values={[["","Select"],["male","Male"],["female","Female"],["other","Other"]]}/><F n="date_of_birth" l="Date of birth" t="date" o/><F n="primary_email" l="Email" t="email" o/><F n="primary_phone" l="Phone" o/></CardContent></Card>
    <Card><CardHeader><h2 className="font-semibold">Employment</h2></CardHeader><CardContent className="grid gap-5 md:grid-cols-3"><F n="employee_number" l="Employee number"/><Sel n="employment_type" l="Employment type" values={[["full_time","Full time"],["part_time","Part time"],["contract","Contract"],["temporary","Temporary"],["volunteer","Volunteer"],["intern","Intern"]]}/><F n="hire_date" l="Hire date" t="date" d={new Date().toISOString().slice(0,10)}/><F n="job_title" l="Job title"/><Lookup n="campus_id" l="Campus" rows={campuses}/><Lookup n="department_id" l="Department" rows={departments}/></CardContent></Card>
    <Card><CardHeader><h2 className="font-semibold">Teaching</h2></CardHeader><CardContent><label className="flex items-center gap-2 text-sm"><input name="is_teacher" type="checkbox" checked={teacher} onChange={e=>setTeacher(e.target.checked)}/> This employee is a teacher</label><p className="mt-2 text-sm text-slate-500">Teaching assignments are managed after the teacher is created.</p></CardContent></Card>
    {teacher ? <Card><CardHeader><h2 className="font-semibold">Portal access</h2></CardHeader><CardContent className="space-y-4"><label className="flex items-center gap-2 text-sm"><input name="enable_portal_access" type="checkbox" checked={portal} onChange={e=>setPortal(e.target.checked)}/> Enable teacher portal access</label>{portal ? <div><Label>Login email *</Label><Input name="login_email" type="email" required/><p className="mt-1 text-sm text-slate-500">A temporary password will be generated. The teacher must change it after first sign-in.</p></div> : null}</CardContent></Card> : null}
    {result.status === "portal-failure" && result.employeeId && result.personId && result.loginEmail ? <><input type="hidden" name="employee_id" value={result.employeeId}/><input type="hidden" name="person_id" value={result.personId}/><input type="hidden" name="login_email" value={result.loginEmail}/><Button formAction={retryAction} type="submit" disabled={retryPending} variant="secondary">Retry portal access</Button></> : null}
    {result.status === "existing-account" && result.canLink && result.employeeId && result.personId && result.loginEmail ? <div className="space-y-2 rounded-xl border border-amber-300 bg-amber-50 p-3"><p className="text-sm">An account already exists for this email address.</p><input type="hidden" name="employee_id" value={result.employeeId}/><input type="hidden" name="person_id" value={result.personId}/><input type="hidden" name="login_email" value={result.loginEmail}/><Button formAction={linkAction} type="submit" disabled={linkPending} variant="secondary">Link existing account</Button><Link className="ml-3 text-sm underline" href="/app/staff/new">Use different email</Link></div> : null}
    {result.status === "portal-success" && result.temporaryPassword ? <Credentials email={result.loginEmail!} password={result.temporaryPassword} shown={shown} toggle={()=>setShown(!shown)}/> : null}
    {result.status === "employee-success" && result.employeeId ? <Link href={`/app/staff/${result.employeeId}`} className="text-sm font-medium underline">View employee record</Link> : null}
    <div className="flex justify-end"><Button disabled={pending}>{pending ? "Creating..." : teacher ? "Create teacher" : "Create employee"}</Button></div>
  </form>;
}
function Credentials({email,password,shown,toggle}:{email:string;password:string;shown:boolean;toggle:()=>void}) { const copy=(v:string)=>navigator.clipboard?.writeText(v); return <div className="space-y-3 rounded-xl border border-amber-300 bg-amber-50 p-4"><p className="font-semibold">Teacher created successfully</p><p>Portal access enabled</p><p>Login email: <code>{email}</code></p><p>Temporary password: <code>{shown ? password : "••••••••••••"}</code></p><div className="flex gap-2"><Button type="button" variant="secondary" onClick={toggle}>{shown ? "Hide" : "Show"}</Button><Button type="button" variant="secondary" onClick={()=>copy(email)}>Copy email</Button><Button type="button" variant="secondary" onClick={()=>copy(password)}>Copy password</Button></div><p className="text-sm">Give these credentials to the teacher. They must change the temporary password after signing in.</p><p className="text-sm">This temporary password will not be shown again.</p></div> }
function F({n,l,t="text",d,o=false}:{n:string;l:string;t?:string;d?:string;o?:boolean}) { return <div><Label>{l}{o?"":" *"}</Label><Input name={n} type={t} defaultValue={d} required={!o}/></div> }
function Sel({n,l,values}:{n:string;l:string;values:[string,string][]}) { return <div><Label>{l} *</Label><Select name={n} defaultValue={values[0]?.[0] ?? ""}>{values.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></div> }
function Lookup({n,l,rows}:{n:string;l:string;rows:any[]}) { return <div><Label>{l}</Label><Select name={n}><option value="">Select</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></div> }
